name: "Test Python"

on:
  push:
    paths-ignore:
    - 'docs/**'

# Our test suite should cover:
# - Compatibility with the most recent versions of Python, Wagtail and Django
# - at least one test run for older supported version of Python, Wagtail and Django
# - a test run against Django's git main branch (allowing failures)
# - a test run against Wagtail's git main branch (allowing failures)

# Current configuration:
# - python 3.9, django 3.2, wagtail 2.14 (+ linting and other checks)
# - python 3.8, django 3.1, wagtail 2.13
# - python 3.7, django 3.1, wagtail 2.12
# - python 3.6, django 3.1, wagtail 2.12

jobs:
  test-current:
    name: With current dependency versions
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "Django>=3.2,<3.3"
          pip install "Wagtail>=2.14,<2.15"
      - name: âœ… Check for missing migrations
        run: django-admin makemigrations --check --noinput
      - name: ðŸ§ª Run tests
        run: pytest --junitxml=junit/test-results.xml --cov=querystring_tag

  test-legacy:
    name: With older dependency versions
    needs: test-current
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    strategy:
      matrix:
        include:
          - python: 3.8
            wagtail: "Wagtail>=2.13,<2.14"
            django: Django>=3.1,<3.2
          - python: 3.7
            wagtail: "Wagtail>=2.12,<2.13"
            django: Django>=3.1,<3.2
          - python: 3.6
            wagtail: "Wagtail>=2.12,<2.13"
            django: Django>=3.1,<3.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: ðŸ§ª Run tests
        run: pytest

  test-latest:
    name: With main Django/Wagtail branches
    needs: test-legacy
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    strategy:
      matrix:
        include:
          - django: "git+https://github.com/django/django.git@main#egg=Django"
            wagtail: Wagtail>=2.14,<2.15
          - django: Django>=3.2,<3.3
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
      - name: ðŸ§ª Run tests
        run: pytest
