name: "Test Python"

on:
  push:
    paths-ignore:
    - 'docs/**'

# Our test suite should cover:
# - Compatibility with the most recent versions of Python and Django
# - at least one test run for older supported version of Python and Django
# - a test run against Django's git main branch (allowing failures)

# Current configuration:
# - python 3.9, django 4.0 (+ linting and other checks)
# - python 3.8, django 3.2
# - python 3.7, django 3.1

jobs:
  test-stable:
    name: Test with latest supported dependencies
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "Django>=4.0,<5.0"
      - name: ðŸ§ª Run tests
        run: pytest --junitxml=junit/test-results.xml --cov=querystring_tag

  test-legacy:
    name: Test with older dependencies
    needs: test-stable
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    strategy:
      matrix:
        include:
          - python: 3.8
            django: Django>=3.2,<4.0
          - python: 3.7
            django: Django>=3.1,<3.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
      - name: ðŸ§ª Run tests
        run: pytest

  test-latest:
    name: Test against Django main branch
    needs: test-legacy
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    strategy:
      matrix:
        include:
          - django: "git+https://github.com/django/django.git@main#egg=Django"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: â¬‡ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install "${{ matrix.django }}"
      - name: ðŸ§ª Run tests
        run: pytest
